[package]
name = "expected_variable"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
case = "1.0.0"
edit-distance = "2.1.0"
strum = "0.25.0"
